FROM node:12.19.0-alpine
ENV NODE_ENV=production

WORKDIR /app

COPY ["package.json", "yarn.lock*", "./"]
RUN yarn install --production && mv node_modules ./
COPY . .

CMD ["node", "dist/server.js"]